name: Publish PDF from markdown docs to GitHub Releases

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create filelist
        id: filelist
        run: |
          mkdir output
          echo "::set-output name=files::$(find .docs/ -name '*.md')"

      - uses: docker://pandoc/latex:2.19
        with:
          args: --output=output/result.pdf ${{ steps.filelist.outputs.files }}

      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: output

      - name: Check output
        run: |
          ls -l output

  release-content:
    runs-on: ubuntu-latest
    needs: [ convert_via_pandoc ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v2
        with:
          name: output
          
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./**/*.pdf
          tag_name: v${{ github.run_number }}-${{ github.sha }}
          name: Release V${{ github.run_number }}
